services:
  web:
    image: odoo:19.0
    depends_on:
      - db
    command: >
      odoo -c /etc/odoo/odoo.conf
      --without-demo=all
    ports:
      - "8102:8069"  # Cambiado de 8101 a 8102 para evitar conflictos
    volumes:
      - odoo19-web-data:/var/lib/odoo  # Cambiado para diferenciar el volumen de Odoo 18
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons/custom-addons
#      - ./addons:/mnt/extra-addons/custom-addons
    networks:
      - webnet
    environment:
      - HOST=db
      - PORT=5432
      - USER=odoo
      - PASSWORD=odoo

  db:
    image: postgres:16
    ports:
      - "6435:5432"  # Cambiado de 6434 a 6435 para evitar conflictos
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo19-db-data:/var/lib/postgresql/data  # Cambiado para diferenciar el volumen de Odoo 18
    networks:
      - webnet

volumes:
  odoo19-web-data:  # Nombre de volumen cambiado
  odoo19-db-data:  # Nombre de volumen cambiado

networks:
  webnet:
